const randomData = [
	{
		id: 1,
		title: "Title",
		price: "120",
		text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati alias id enim necessitatibus quaerat soluta?",
		category: "laptop",
		image: "./categoryImages/pc.jpg",
	},
	{
		id: 2,
		title: "Title",
		price: "70",
		text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae officia mollitia soluta quia eligendi incidunt excepturi, perferendis reiciendis aut ut commodi itaque, quibusdam fugiat corrupti?",
		category: "cartoon",
		image: "./categoryImages/toy-car.jpg",
	},
	{
		id: 3,
		title: "Title",
		price: "230",
		text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati alias id enim necessitatibus quaerat soluta? Lorem ipsum dolor, sit amet consectetur adipisicing.",
		category: "wallpaper",
		image: "./categoryImages/car.jpg",
	},
	{
		id: 4,
		title: "Title",
		price: "69",
		text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis ratione nam consectetur quibusdam cupiditate voluptas mollitia eligendi. Consequatur at iure voluptate ullam.",
		category: "cartoon",
		image: "./categoryImages/tom.jpg",
	},
	{
		id: 5,
		title: "Title",
		price: "97",
		text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam, mollitia sed explicabo doloremque tenetur illo officia, libero adipisci a natus, quisquam nesciunt magni minus commodi nihil repellendus eligendi rerum error?",
		category: "laptop",
		image: "./categoryImages/pc-1.jpg",
	},
	{
		id: 6,
		title: "Title",
		price: "59",
		text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam, mollitia sed nesciunt magni minus commodi nihil repellendus eligendi rerum error?",
		category: "laptop",
		image: "./categoryImages/pc-2.jpg",
	},
	{
		id: 7,
		title: "Title",
		price: "132",
		text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam, mollitia sed nesciunt magni minus commodi nihil repellendus eligendi rerum error illo officia, libero adipisci a natus, quisquam nesciunt",
		category: "wallpaper",
		image: "./categoryImages/ai-dollar.jpg",
	},
	{
		id: 8,
		title: "Title",
		price: "261",
		text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam, mollitia sed nesciunt magni minus commodi nihil repellendus eligendi rerum error illo officia, libero adipisci a natus, quisquam nesciunt Lorem ipsum dolor sit amet.",
		category: "graphics",
		image: "./categoryImages/slide5.jpg",
	},
	{
		id: 9,
		title: "Title",
		price: "101",
		text: "Lorem ipsum dolor sit amet consectetur cupiditate voluptas mollitia eligendi. Consequatur at iure voluptate ullam.dus eligendi rerum error illo officia, libero adipisci a natus, quisquam nesciunt",
		category: "cartoon",
		image: "./categoryImages/spider-man.jpg",
	},
	{
		id: 10,
		title: "Title",
		price: "73",
		text: "ipsum dolor sit amet consectetur adipisicing elit. Nam, mollitia sed nesciunt magni. Dus eligendi rerum error illo officia, libero adipisci a natus, quisquam nesciunt",
		category: "laptop",
		image: "./categoryImages/pc-3.jpg",
	},
	{
		id: 11,
		title: "Title",
		price: "341",
		text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo iusto voluptate praesentium corporis maxime? Accusamus maxime iusto nostrum perferendis nobis! Nesciunt harum iusto odit soluta hic modi.",
		category: "wallpaper",
		image: "./categoryImages/gadgets.jpg",
	},
	{
		id: 12,
		title: "Title",
		price: "341",
		text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae, laborum? Nostrum impedit amet iste dolorem architecto laboriosam dolor fugit?",
		category: "graphics",
		image: "./categoryImages/slide4.jpg",
	},
];

export default randomData;
